package com.lanchat.server.handler;

import com.fasterxml.jackson.databind.node.ObjectNode;
import com.lanchat.common.protocol.Envelope;
import com.lanchat.common.protocol.MessageType;
import com.lanchat.server.ClientHandler;
import com.lanchat.server.service.PresenceTracker;

import java.util.concurrent.ConcurrentHashMap;

/**
 * Server-side relay for file transfers.
 *
 * The server never touches the file bytes — it only relays:
 *   FILE_OFFER  → forwarded to receiver
 *   FILE_ACCEPT → forwarded to sender (triggers chunk sending)
 *   FILE_CHUNK  → forwarded to receiver
 *   FILE_DONE   → forwarded to receiver, transfer cleaned up
 *
 * transferId (UUID) is generated by the sender and used as the correlation key
 * so multiple concurrent transfers between different pairs don't interfere.
 *
 * Android note: The Android client uses the same protocol — it calls
 *   MessageSender.send(FILE_OFFER/CHUNK/DONE)  to send,
 *   handles FILE_OFFER/ACCEPT/CHUNK/DONE in MessageListener  to receive.
 */
public final class FileTransferHandler {

    // transferId → sender's handler  (pending — offer sent, waiting for accept)
    private static final ConcurrentHashMap<String, ClientHandler> pendingTransfers
            = new ConcurrentHashMap<>();

    // transferId → receiver's handler  (active — chunks flowing)
    private static final ConcurrentHashMap<String, ClientHandler> activeTransfers
            = new ConcurrentHashMap<>();

    private FileTransferHandler() {}

    // ── Offer ────────────────────────────────────────────────────────

    /** Sender sends FILE_OFFER → server forwards to receiver. */
    public static void offer(ClientHandler sender, Envelope env) {
        String to         = env.payload.get("to").asText();
        String transferId = env.payload.get("transferId").asText();

        ClientHandler receiver = PresenceTracker.get(to);
        if (receiver == null) {
            sender.sendError("USER_NOT_FOUND",
                    "Cannot send file: '" + to + "' is offline");
            return;
        }

        pendingTransfers.put(transferId, sender);

        // Stamp sender's username so receiver knows who is sending
        ((ObjectNode) env.payload).put("from", sender.getUsername());
        receiver.send(new Envelope(MessageType.FILE_OFFER, env.payload));

        System.out.println("[FILE] Offer: " + sender.getUsername()
                + " → " + to + " [" + transferId + "]");
    }

    // ── Accept ───────────────────────────────────────────────────────

    /** Receiver sends FILE_ACCEPT → server notifies sender to start chunking. */
    public static void accept(ClientHandler receiver, Envelope env) {
        String transferId = env.payload.get("transferId").asText();
        ClientHandler sender = pendingTransfers.remove(transferId);

        if (sender == null) {
            receiver.sendError("TRANSFER_NOT_FOUND",
                    "No pending transfer with ID: " + transferId);
            return;
        }

        activeTransfers.put(transferId, receiver);
        sender.send(new Envelope(MessageType.FILE_ACCEPT, env.payload));

        System.out.println("[FILE] Accepted: " + transferId);
    }

    // ── Chunk ────────────────────────────────────────────────────────

    /** Sender sends FILE_CHUNK → server relays to receiver. */
    public static void chunk(ClientHandler sender, Envelope env) {
        String transferId = env.payload.get("transferId").asText();
        ClientHandler receiver = activeTransfers.get(transferId);

        if (receiver == null) {
            sender.sendError("TRANSFER_NOT_FOUND",
                    "Transfer not active: " + transferId);
            return;
        }

        receiver.send(new Envelope(MessageType.FILE_CHUNK, env.payload));
    }

    // ── Done ─────────────────────────────────────────────────────────

    /** Sender signals last chunk sent → server relays FILE_DONE and cleans up. */
    public static void done(ClientHandler sender, Envelope env) {
        String transferId = env.payload.get("transferId").asText();
        ClientHandler receiver = activeTransfers.remove(transferId);

        if (receiver != null) {
            receiver.send(new Envelope(MessageType.FILE_DONE, env.payload));
            System.out.println("[FILE] Complete: " + transferId);
        }
    }

    /** Clean up any transfers involving a disconnected user. */
    public static void onUserDisconnected(String username) {
        // Remove pending transfers where this user was the sender
        pendingTransfers.entrySet().removeIf(e ->
                e.getValue().getUsername() != null
                && e.getValue().getUsername().equals(username));

        // Remove active transfers where this user was the receiver
        activeTransfers.entrySet().removeIf(e ->
                e.getValue().getUsername() != null
                && e.getValue().getUsername().equals(username));
    }
}
